# Generated by Django 2.0.10 on 2019-02-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine')], default='M', max_length=1)),
                ('avatar', models.URLField(blank=True, default='https://scontent-bog1-1.cdninstagram.com/vp/08b4774c7bdd7a1615e2b66476150437/5CD15391/t51.2885-19/s150x150/33940709_2091657174447047_1561961433825017856_n.jpg?_nc_ht=scontent-bog1-1.cdninstagram.com')),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_by', to='users.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='following_users', to='users.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
