# Generated by Django 2.0.10 on 2019-01-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190114_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('not-specified', 'Not specified')], max_length=80, null=True),
        ),
    ]
